# Generated by Django 2.2.5 on 2020-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_title', models.CharField(max_length=50)),
                ('django_image', models.ImageField(upload_to='images/')),
                ('django_summery', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='PythonBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_title', models.CharField(max_length=50)),
                ('python_image', models.ImageField(upload_to='images/')),
                ('python_summery', models.CharField(max_length=100000)),
            ],
        ),
    ]
